### ISSUE TITLE
[BUG] 图标显示有问题

### ISSUE THREAD

**Issue by kands-code** [Icalingua/Icalingua#145]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

appimage版本，任务栏图标为x server样式，aur版本，菜单栏缺失图标，且任务栏图标为x server图标

**To Reproduce / 复现过程**

kde桌面环境，archlinux

**Expected behavior / 预期的结果**

任务栏图标应该为聊天图标，或者electron图标，而不是x server图标

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![图片](https://user-images.githubusercontent.com/59006329/129434325-d4d8a0fb-db56-4009-8d09-9a31a0b2f85d.png)

**System informations / 系统信息**
 - OS: [e.g. Arch Linux] Arch Linux
 - Version [e.g. 2.1.4] 2.1.5

**Comment by kands-code** [comment]
主要是发现close的issue不能reopen，所以才又新开了一个issue，这个问题前几个版本有人提到过

**Comment by kands-code** [comment]
补充一个，2.1.5版文件上传也有点问题，无法上传文件

**Comment by CharlieYu4994** [comment]
> 补充一个，2.1.5版文件上传也有点问题，无法上传文件

貌似并非无法上传，重新传一次是秒传的……

**Comment by kands-code** [comment]
> > 补充一个，2.1.5版文件上传也有点问题，无法上传文件
> 
> 貌似并非无法上传，重新传一次是秒传的……

确实，应该是我的文件有问题，我换了个文件就可以上传了，不过图标问题是实在的

**Comment by kands-code** [comment]
诶？已经修复了嘛？我通过appimage使用的时候还是没有图标显示，而其他appimage包是可以正常显示的

这是 Icalingua 的图标效果

![图片](https://user-images.githubusercontent.com/59006329/142734253-6dd9cc99-5c16-4e8b-939e-006856e82dfe.png)

这是其他 appimage 程序的效果

![图片](https://user-images.githubusercontent.com/59006329/142734324-44e010d9-e39f-45d8-903f-e41d83b0b78d.png)

- 桌面环境 Plasma 5.23.3
- 系统 Archlinux
- 内核 5.15.2-zen1-1-zen
- 主题 Breeze Light [Plasma], Breeze [GTK2/3]
- 图标主题 Papirus-Light [Plasma], Papirus-Light [GTK2/3]
- Icalingua版本
![图片](https://user-images.githubusercontent.com/59006329/142734785-231953b8-70e5-4297-a9e9-f263b05a549b.png)

**Comment by kands-code** [comment]
抱歉打扰了，刚刚又刷新了一下系统缓存，图标好了
