### ISSUE TITLE
[Feature Request] 希望同一张图只保留一个图片查看器

### ISSUE THREAD

**Issue by sukanka** [Icalingua/Icalingua#232]
**Is your feature request related to a problem? Please describe.**

在当前（2.2.3） icalingua 里面，重复点击一张图片会打开多个重复图片查看窗口，图上标号已经到5了，5个都是一样的窗口。
![Screenshot_20210924_223447](https://user-images.githubusercontent.com/31362108/134692648-c9e13836-66b9-4130-a0b7-c009b01ed4bf.png)

**Describe the solution you'd like**

希望的行为是至多只有一个图片窗口（即使是两张不同的图也不能同时开，有这个需求的就自己保存到本地查看吧）

**Describe alternatives you've considered**

**Additional context**

**Comment by dragove** [comment]
只保留一个有什么好处呢？官方qq就是多个窗口，你可以打开后关闭再点开另一个。倒是同一张图片只打开一个还挺合理的。

**Comment by sukanka** [comment]
> 只保留一个有什么好处呢？官方qq就是多个窗口，你可以打开后关闭再点开另一个。倒是同一张图片只打开一个还挺合理的。

之前是因为我觉得判断是不是同一张图比较麻烦，不过有人指出 
> 用图片的名字/hash作为窗口的ID, 如果某个ID的窗口存在就直接调到前面, 不存在就打开新的窗口

确实就可以不重复打开图片，多个图片多个窗口，这样就很不错。
