### ISSUE TITLE
[BUG] 互动标识弹窗两次

### ISSUE THREAD

**Issue by tsurumi-yizhou** [Icalingua/Icalingua#233]
**Describe the bug / 描述**
互动标识弹窗两次

**To Reproduce / 复现过程**
点击菜单栏好友昵称，点击下拉菜单中的互动标识

**Expected behavior / 预期的结果**
如题

**Screenshots / 截图**
[![4sOlrj.png](https://z3.ax1x.com/2021/09/25/4sOlrj.png)](https://imgtu.com/i/4sOlrj)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Comment by Clansty** [comment]
@tsurumi-yizhou 下次记得写标题

**Comment by tsurumi-yizhou** [comment]
> @tsurumi-yizhou 下次记得写标题

希望没有下次/笑
另外，OS：Archlinux, Version：2.2.3

**Comment by MemoryShadow** [comment]
我也遇到了同样的问题
OS信息：
* OS: [Manjaro Linux]
* Version [5.13.19-2-MANJARO(AMD64)]

**Comment by Clansty** [comment]
@MemoryShadow 我也遇到了同样的问题

**Comment by Clansty** [comment]
现在是不是没有这个问题了
