### ISSUE TITLE
[BUG]在deepin20.2.3上状态栏会显示两个图表

### ISSUE THREAD

**Issue by yimisunrise** [Icalingua/Icalingua#244]
**Describe the bug / 描述**
在deepin20.2.3上状态栏会显示两个图表

**To Reproduce / 复现过程**
在deepin20.2.3上正常启动兵登录QQ

**Expected behavior / 预期的结果**
只需要有一个状态栏图表

**Screenshots / 截图**
无

**System information / 系统信息**
 - OS: [Deepin]
 - Version [20.2.3]

**Additional context / 附加信息**
无

**Comment by sukanka** [comment]
重复问题，#68

**Comment by Clansty** [comment]
@yimisunrise 是 Deepin 的问题，之前已经有人反馈过了，目前上游似乎已经修复了，但是还没更新上。UOS 也有这个问题

**Comment by CoelacanthusHex** [comment]
@Clansty DDE 修复进发版很慢的，之前 Qv2ray 报的那个代理的修复我记得用了将近一年
