### ISSUE TITLE
[BUG]聊天内容内容错群显示

### ISSUE THREAD

**Issue by wsyzbsj** [Icalingua/Icalingua#269]
**Describe the bug / 描述**
其他群的聊天内容错误显示在当前没有对话的群聊中且与之前聊天内容无明显区分

**To Reproduce / 复现过程**
1.选择某一安静的群聊，静置一段时间（比如五分钟）
2.能看到其他群聊的内容错误出现在了当前群聊中

**Expected behavior / 预期的结果**
没人讲话，应当是保持原状

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/44899578/136650714-2199396d-babb-4cf7-ba2f-3846424c7e12.png)

**System information / 系统信息**
 - OS:Arch Linux
 - Version:2.3.2-1

**Comment by lixiang810** [comment]
这个项目有两个作者在你的学校，包括主作者。建议面对面提issue（

**Comment by wsyzbsj** [comment]
切回来就不在了，原本的群也有，数据库是SQLite.
