### ISSUE TITLE
[BUG] 保存的对话框打不开了

### ISSUE THREAD

**Issue by Clansty** [Icalingua/Icalingua#274]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

导出数据功能都没有反应

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
![图片](https://user-images.githubusercontent.com/18461360/137251463-1ef0a788-07e0-4448-b94d-476a187442e5.png)

这似乎是一个 Electron 的 bug。Electron 15 好像 bug 很多的样子

看来换直接 DBus 调用迫在眉睫了

**Comment by CoelacanthusHex** [comment]
> ![图片](https://user-images.githubusercontent.com/18461360/137251463-1ef0a788-07e0-4448-b94d-476a187442e5.png)
> 
> 这似乎是一个 Electron 的 bug。Electron 15 好像 bug 很多的样子
> 
> 看来换直接 DBus 调用迫在眉睫了

直接 dbus 调用你就只能 GTK 原生和 PortalNative 二选一了
