### ISSUE TITLE
[BUG] 切换会话后，回复状态仍保留且仍能发送

### ISSUE THREAD

**Issue by Sciroccogti** [Icalingua/Icalingua#286]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

双击某消息准备回复时，如果切换到其它会话，该回复状态仍然保留，并且仍能以回复的形式发出。

**To Reproduce / 复现过程**

1. 在 A 会话中，双击某消息以进入回复模式
2. 切换到 B 会话
3. 发送消息

**Comment by sukanka** [comment]
这是 feature, 不是 bug, 参考 https://github.com/Icalingua/Icalingua/issues/141

**Comment by Clansty** [comment]
本来就是这么设计的

**Comment by Sciroccogti** [comment]
原来是 feature 不是 bug 啊😂

但是还是有一点问题：跨会话回复的消息，在 Icalingua 上显示的是错误的引用，但是在其它平台（譬如手机QQ）上，显示的是正确的。

|Icalingua（错误）|手机QQ（正确）|
|---|---|
|![image](https://user-images.githubusercontent.com/32357397/137661294-9ebe21c8-7866-4d6e-b3d8-3929d69df16f.png)|![IMG_20211018_104253](https://user-images.githubusercontent.com/32357397/137661387-dba24fd8-7d16-4b36-b3d6-d94c51be4ea4.jpg)|

我回复的是 另一个会话中 GSW 的消息“什么PPT”，手机QQ等官方平台中显示正确，但是在Icalingua 中显示我回复的是别的消息。
