### ISSUE TITLE
[Feature Request] Face 表情

### ISSUE THREAD

**Issue by XYY1411** [Icalingua/Icalingua#304]
Icalingua 找 QQ 原生表情太麻烦了，找一个表情找了 1 min，而且表情按字典序排布而不是数字大小，希望能完善以下，并增加一类似 QQ 快捷键(/xx)的功能。

**Comment by ambition-echo** [comment]
这个表情的排序确实有问题，1过了是100,然后101这种，建议命名直接写000,统一按三位进行命名。
