### ISSUE TITLE
点击通知后错误地启动了fdm

### ISSUE THREAD

**Issue by aimerneige** [Icalingua/Icalingua#32]
系统版本 `Pop!_OS 20.04 LTS x86_64`

electron-qq 版本 `1.5.0` deb包安装

Free Download Manager 版本 `6.14.2.3973 (8e79e451)`

错误描述：

收到消息后点击通知会启动fdm而不是electron-qq

卸载fdm后可以成功启动electron-qq

但是在安装fdm的情况下无法使用系统通知启动electron-qq 系统通知总是会拉起fdm

**Comment by aimerneige** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/51701792/121804937-85a29300-cc7b-11eb-934c-458d178ce957.gif)

重新安装后问题依然可以复现，启动electron-qq后会拉起fdm

**Comment by CoelacanthusHex** [comment]
感觉是 scheme register 的问题……

**Comment by Clansty** [comment]
@CoelacanthusHex 我好像没有注册 scheme

**Comment by CoelacanthusHex** [comment]
@Clansty 那大概是fallback的时候出现了奇怪的顺序（或者是Windows的通知拉起机制有奇怪的问题

**Comment by aimerneige** [comment]
在没有安装 icalingua 的系统上使用其他软件的时候也出现了同样的问题，这个应该是 gnome 或 fdm 的问题，我觉得可以close了。
