### ISSUE TITLE
[BUG]从2.3.2更新到2.4.0后无法更新数据库

### ISSUE THREAD

**Issue by Neubulae** [Icalingua/Icalingua#322]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
卡死在数据库升级，然后oom被杀掉

**To Reproduce / 复现过程**
启动

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
```
➜  ~ icalingua
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
icalingua> (node:3329) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `electron --trace-warnings ...` to show where the warning was created)
Aria2 RPC connected
info 正在升级数据库
Applying SQL Storage Provider Update:
 Version 7
 Fill the Rabbit Hole

<--- Last few GCs --->

[3329:0x351800498000]    65163 ms: Scavenge (reduce) 3820.9 (3950.8) -> 3820.6 (3953.8) MB, 18.2 / 0.2 ms  (average mu = 0.901, current mu = 0.864) allocation failure 
[3329:0x351800498000]    65233 ms: Scavenge (reduce) 3824.1 (3953.8) -> 3823.9 (3957.0) MB, 16.0 / 0.2 ms  (average mu = 0.901, current mu = 0.864) allocation failure 
[3329:0x351800498000]    65338 ms: Scavenge (reduce) 3827.2 (3957.0) -> 3827.1 (3958.8) MB, 49.1 / 0.3 ms  (average mu = 0.901, current mu = 0.864) allocation failure 


<--- JS stacktrace --->

[3329:1113/232422.059479:ERROR:node_bindings.cc(143)] Fatal error in V8: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
/usr/bin/icalingua：行 2:  3329 段错误               （核心已转储）electron /usr/share/icalingua/icalingua.asar "$@"


```

**System information / 系统信息**
 - OS: Arch Linux
 - Version: 2.4.0

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Henry-ZHR** [comment]
我这也是

```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/client.js:295:26)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async Runner.ensureConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:30:19) {
  sql: undefined,
  bindings: undefined
}
```
整个终端都是这个错误，再上面的就没保留了

**Comment by Neubulae** [comment]
> 我这也是
> 
> ```
> KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
>     at Client_SQLite3.acquireConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/client.js:295:26)
>     at runMicrotasks (<anonymous>)
>     at runNextTicks (node:internal/process/task_queues:61:5)
>     at listOnTimeout (node:internal/timers:526:9)
>     at processTimers (node:internal/timers:500:7)
>     at async Runner.ensureConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:259:28)
>     at async Runner.run (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:30:19) {
>   sql: undefined,
>   bindings: undefined
> }
> ```
> 
> 整个终端都是这个错误，再上面的就没保留了

是的，第一次更新的时候终端给我刷了大概几十行这个

**Comment by Neubulae** [comment]
> 我这也是
> 
> ```
> KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
>     at Client_SQLite3.acquireConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/client.js:295:26)
>     at runMicrotasks (<anonymous>)
>     at runNextTicks (node:internal/process/task_queues:61:5)
>     at listOnTimeout (node:internal/timers:526:9)
>     at processTimers (node:internal/timers:500:7)
>     at async Runner.ensureConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:259:28)
>     at async Runner.run (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:30:19) {
>   sql: undefined,
>   bindings: undefined
> }
> ```
> 
> 整个终端都是这个错误，再上面的就没保留了

是的，第一次更新的时候终端给我刷了大概几十行这个

**Comment by Clansty** [comment]
@lixiang810

**Comment by happi0** [comment]
遇到相同的问题, 我的环境也是arch
同时安装 了一下测试版,icalingua 2.4.0_20211113130247-1
也有相同的问题

**Comment by lixiang810** [comment]
在改了。周二前应该会修复。在此之前请尽量不要使用 SQLite 数据库。

**Comment by lixiang810** [comment]
arch 用户请下载 https://github.com/Icalingua/Icalingua/suites/4347486981/artifacts/114060158 后，解开 zip 文件，并 `sudo pacman -U xxxxx.pkg.tar.zst` ，之后再输入 `icalingua` 启动，观察有无异常。如果无异常，那么升级就成功了。

我需要你们帮忙测试一下，因为我这里并没有这么大体量的数据库。

**Comment by taostart** [comment]
> arch 用户请下载 https://github.com/Icalingua/Icalingua/suites/4347486981/artifacts/114060158 后，解开 zip 文件，并 `sudo pacman -U xxxxx.pkg.tar.zst` ，之后再输入 `icalingua` 启动，观察有无异常。如果无异常，那么升级就成功了。
> 
> 我需要你们帮忙测试一下，因为我这里并没有这么大体量的数据库。

已安装，有效。

**Comment by lixiang810** [comment]
漂亮。马上安排一个 `2.4.1` 版本。

**Comment by Neubulae** [comment]
既然如此，有无办法把数据库迁移到别的上

**Comment by Clansty** [comment]
@Neubulae 暂时还没有做数据库迁移的组件

**Comment by Neubulae** [comment]
已安装，有效

**Comment by happi0** [comment]
> arch 用户请下载 https://github.com/Icalingua/Icalingua/suites/4347486981/artifacts/114060158 后，解开 zip 文件，并 `sudo pacman -U xxxxx.pkg.tar.zst` ，之后再输入 `icalingua` 启动，观察有无异常。如果无异常，那么升级就成功了。
> 
> 我需要你们帮忙测试一下，因为我这里并没有这么大体量的数据库。

我这里无法正常启动, 数据库选择的是Sqlite
```
Gtk-Message: 16:48:52.641: Failed to load module "colorreload-gtk
libva error: vaGetDriverNameByIndex() failed with unknown libva e
[12561:1114/164852.718658:ERROR:sandbox_linux.cc(374)] Initialize
icalingua> (node:12531) Warning: Setting the NODE_TLS_REJECT_UNAU
ure by disabling certificate verification.
(Use `electron --trace-warnings ...` to show where the warning wa
info 正在升级数据库
[Error: alter table `msg1284732495` add column `files` text null
  errno: 1,
  code: 'SQLITE_ERROR'
}
icalingua> (node:12531) UnhandledPromiseRejectionWarning: Error:
ERR_FAILED (-2) loading 'file:///usr/share/icalingua/icalingua.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)
    at Object.emit (node:domain:470:12)
    at Object.topLevelDomainCallback (node:domain:147:15)
    at Object.callbackTrampoline (node:internal/async_hooks:128:24)
(node:12531) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 114)
```

**Comment by lixiang810** [comment]
@happi0 你这个数据库应该不是从2.3.2升级的才对。2.3.2升2.4.0会出一个fill the rabbit hole

**Comment by Universebenzene** [comment]
测了下release里刚刚打包的2.4.1 
```
[29997:1114/194241.402755:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
icalingua> (node:29957) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
info 正在升级数据库
Applying SQL Storage Provider Update:
 Version 7
 Fill the Rabbit Hole
[Error: select count(`_id`) from `msg-151756267` - SQLITE_ERROR: no such table: msg-151756267] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
(node:29957) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///opt/Icalingua/resources/app.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)
    at Object.emit (node:domain:470:12)
    at Object.topLevelDomainCallback (node:domain:147:15)
    at Object.callbackTrampoline (node:internal/async_hooks:128:24)
(node:29957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
用的是deb包解包重打的

**Comment by lixiang810** [comment]
@Universebenzene 你这种情况应该是 2.4.0 迁移到一半的时候出了问题。我的建议是用 SQLite DB Browser 打开 `~/.config/Icalingua/database/eqq(qq号).db` 手动建一个名叫 `msg-151756267` 的表，点击保存。

另外拜见天苯大佬。

**Comment by Universebenzene** [comment]
@lixiang810 完全不懂sqlite，别叫大佬了😭
我去Google怎么用……😞

**Comment by lixiang810** [comment]
有一个叫 SQLite DB Browser 的软件，应该是拿 qt 写的。aur 里面有，gentoo 不知道。

http://www.sqlitebrowser.org/

**Comment by Universebenzene** [comment]
portage里面有，我正在装😷

**Comment by lixiang810** [comment]
如果可能的话，帮我在贴吧发一下通知，让用 SQLite 但还没升 2.4.0 的别升 2.4.0。我贴吧已经卸了，电脑端浏览器 bug 上不了。

**Comment by Universebenzene** [comment]
建了表也不知道写什么，什么都不填就不让点OK……我对sql实在是完全一无所知😞

**Comment by lixiang810** [comment]
啊这……你的聊天记录重要不？不重要的话直接把那个文件删了就行。重要的话可以考虑给我帮忙弄一下。我 tg 的 username 叫 TDNYjsp

**Comment by Universebenzene** [comment]
@lixiang810 随便找另一个表随便仿了一下……然后又报另一个表找不着了……我找下菊苣罢先

**Comment by Neubulae** [comment]
woc一个issue炸出一吨dalao

**Comment by happi0** [comment]
> @happi0 你这个数据库应该不是从2.3.2升级的才对。2.3.2升2.4.0会出一个fill the rabbit hole

一开始正常更新无法连接数据库后, 我自己去找了以前的包安装了, 中间折腾了几下。可能导致数据库损坏了。

由于聊天记录不重要， 删除之后能正常运行了。
