### ISSUE TITLE
[BUG] 托盘图标的工具提示无意义

### ISSUE THREAD

**Issue by timothyqiu** [Icalingua/Icalingua#324]
**Describe the bug / 描述**
托盘图标上出现的工具提示内容无意义。

> **Electron**
> icon

**To Reproduce / 复现过程**
鼠标移到托盘图标上停留一会儿。

**Expected behavior / 预期的结果**
显示当前昵称和在线状态之类的。

**Screenshots / 截图**
![截图_2021-11-14_13-12-36](https://user-images.githubusercontent.com/372476/141668813-6ca57797-6789-451d-b2f9-54656ae8d879.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.4.0（之前版本也是如此）

**Additional context / 附加信息**
无。

**Comment by jiayouba233** [comment]
在Ubuntu系统中，可以修改提醒等级等设置（v2.4.1 #320 这个新版本我还没用山，旧版本可以）

题外话：我看各位用的都是Arch Linux发行版，这个发行版用其他怎么样啊？

**Comment by Clansty** [comment]
#144
