### ISSUE TITLE
可能不合适，只是提个需求

### ISSUE THREAD

**Issue by kanuchang** [Icalingua/Icalingua#334]
System information / 系统信息
loongarch64架构，Loongson-3A5000LL处理器，统信uos系统

今天在系统内置商店中注意到有网友上传微信的wine版本，不知道有没有移植的可能，等官方的可能得猴年马月了。

![image](https://user-images.githubusercontent.com/19322162/142379281-ca23be24-f6a4-4fc4-a239-eccea3557538.png)

**Comment by aimerneige** [comment]
目前好像没有类似oicq的实现了微信通讯协议的库

**Comment by kanuchang** [comment]
不知道Wine有没有针对龙芯的移植版本

**Comment by kanuchang** [comment]
不知道Wine有没有针对龙芯的移植版本

**Comment by aimerneige** [comment]
你可以尝试这个项目 https://github.com/loaden/nspawn-deepinwine

**Comment by sukanka** [comment]
有人打包了适用于loongarch64的 freechat (一个第三方网页版微信客户端），你可以从这里下载到
https://dl.sukanka.com/

**Comment by Clansty** [comment]
freechat 就可以了
