### ISSUE TITLE
[BUG]文件名包含空格时 仅高亮最后一个空格后的文字

### ISSUE THREAD

**Issue by SAFEluren** [Icalingua/Icalingua#338]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
文件名包含空格时 仅高亮最后一个空格后的文字

**To Reproduce / 复现过程**
发送一个文件名包含空格的文件 然后查看

**Expected behavior / 预期的结果**
文件名全部高亮

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/79032826/142716839-2c33a250-902a-4204-af47-138ee1fcdf79.png)

**System information / 系统信息**
 - OS: Manjaro
 - Version 2.4.3
 - ![image](https://user-images.githubusercontent.com/79032826/142716872-967094b2-f110-46a9-a580-f5e18303cc40.png)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
本来不该高亮的

只是你的 `Beyond.zip` 被识别成链接了

**Comment by lixiang810** [comment]
这不是那个 MC 整合包吗？有服务器玩不，拉我一个

**Comment by CoelacanthusHex** [comment]
@Clansty 那说明regex写的不够好
