### ISSUE TITLE
[BUG] 更新 2.4.3 后软件打开黑屏

### ISSUE THREAD

**Issue by greenhat616** [Icalingua/Icalingua#340]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

**To Reproduce / 复现过程**
`electron13 /usr/share/icalingua/icalingua.asar` 异常
`electron  /usr/share/icalingua/icalingua.asar` 正常 # electron 15
**Expected behavior / 预期的结果**
修复问题
**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/41122242/142845558-15c403a3-95c0-4ddc-a4aa-84ebcd16913a.png)
![图片](https://user-images.githubusercontent.com/41122242/142845722-1e0bb73f-1ae2-442c-8f72-539db7e84ea8.png)

If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: Arch Linux
 - Version 2.4.3

```
                   -`                    a632079@a632079-laptop 
                  .o+`                   ---------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Umi Pro II Series GM5MP0Y Standa 
               `+oooooo:                 Kernel: 5.15.4-arch1-1 
               -+oooooo+:                Uptime: 3 mins 
             `/:-:++oooo+:               Packages: 1101 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 41.1 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Orchis-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: candy-icons [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10875H (16) @ 5.100GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 2060 Mobile 
 `++:.                           `-/+/   Memory: 1995MiB / 32003MiB 
 .`                                 `/
                                                                 
                                                                 
```
Compositor: Wayland

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

已经删除 `~/.config/icalingua` , 存在的情况下不管哪个方式都黑屏;
由于不知道日记存储在哪,所以此条不做反馈.

**Comment by Clansty** [comment]
请问你用的是 Wayland 嘛，如果是的话直接打开 electron13 会黑屏嘛

以及可以按下 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> 看看有什么错误嘛

**Comment by greenhat616** [comment]
> 

是的,使用 Wayland
electron15 打开不会黑屏, electron13打开会黑屏
`Ctrl` + `Shift` + `I` 没有反应

**Comment by greenhat616** [comment]
@Clansty 通过其他软件的测试, 应该是 electron 问题, 导致没有渲染出来.
在某个支持 `--enable-features=UseOzonePlatform --ozone-platform=wayland` flag 的软件上 使用 electron13 运行可正常启动.

所以我认为这个是上游问题, 且和 https://github.com/Icalingua/Icalingua/issues/321 相关
