### ISSUE TITLE
[BUG] 启动后显示“正在升级数据库”，等待一段时间后开始不断刷报错

### ISSUE THREAD

**Issue by nerimoe** [Icalingua/Icalingua#341]
Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
启动后显示“正在升级数据库”，等待一段时间后开始不断循环此段报错

> KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
>     at Client_MySQL.acquireConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/client.js:295:26)
>     at runMicrotasks (<anonymous>)
>     at runNextTicks (internal/process/task_queues.js:58:5)
>     at listOnTimeout (internal/timers.js:523:9)
>     at processTimers (internal/timers.js:497:7)
>     at async Runner.ensureConnection (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:259:28)
>     at async Runner.run (/usr/share/icalingua/icalingua.asar/node_modules/knex/lib/execution/runner.js:30:19) {
>   sql: undefined,
>   bindings: undefined

**To Reproduce / 复现过程**
启动
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![图片](https://user-images.githubusercontent.com/57009175/142882946-6b3b3b1e-b61e-4069-94d1-e6f6394a7ceb.png)

**System information / 系统信息**
 - OS: archlinux
 - Version icalingua-2.4.3-1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
数据库使用mysql/mariadb

**Comment by nerimoe** [comment]
删除~/.config并更换为sqlite可以成功启动，换回mysql就依然会这样子

需要删除掉数据库吗（？

**Comment by lixiang810** [comment]
@nerimoe 艹了，适配了pgSQL和SQLite，唯独没想到MySQL，我想想办法，大概明天下午写出来
别删库

**Comment by lixiang810** [comment]
@nerimoe 顺便问一下你这个数据库体量大概多大

**Comment by nerimoe** [comment]
> https://github.com/Icalingua/Icalingua/actions/runs/1494280987 用这里面的版本试试看，如果没问题我就 release 了

启动成功

**Comment by lixiang810** [comment]
6M是压缩后的还是.sql？
按道理这个体量不应该不能并发才对。你的MySQL是在服务器上而不是本机上吗？

**Comment by nerimoe** [comment]
.sql，服务器上

**Comment by lixiang810** [comment]
我认为是你的 MySQL 服务器搞了连接数/并发限制，抑或存在一定性能问题，从而导致升级失败。

给你的那一份代码对别人来说应该会数十倍延长升级时间，所以我在考虑拿那个作为 fallback。

**Comment by nerimoe** [comment]
mariadb的连接数和并发一直都是archlinux下包内的默认设置

用f9791ce升级完后回到release版就正常了(
