### ISSUE TITLE
[BUG]在deepin系统下托盘图标重复的问题

### ISSUE THREAD

**Issue by yimisunrise** [Icalingua/Icalingua#363]
**Describe the bug / 描述**
在deepin系统下，系统托盘图标会出现重复，并且任务栏活动窗口的图标也没有。希望优化一下，感谢！
![image](https://user-images.githubusercontent.com/13777332/144963745-3fe0fae5-340e-4106-9faf-bdf9e5965807.png)

**Comment by sukanka** [comment]
这确实是个重复的问题，#68

**Comment by Clansty** [comment]
@yimisunrise 这是第几次了

**Comment by yimisunrise** [comment]
> 
好吧 ，这个确实是重复问题。只是我确实很想解决这个问题！

**Comment by yimisunrise** [comment]
问题依然存在，该问题重复提交！真心希望有一个优雅的解决方案！

**Comment by sukanka** [comment]
> > 
> 
> 好吧 ，这个确实是重复问题。只是我确实很想解决这个问题！

解决方案已经在#68中给出。
这是deepin的问题
https://github.com/Icalingua/Icalingua/issues/68#issuecomment-891533310

**Comment by Clansty** [comment]
@yimisunrise 这是 dde 那边的问题，与我们无关，我们没法修复

**Comment by yimisunrise** [comment]
> > > 
> > 
> > 
> > 好吧 ，这个确实是重复问题。只是我确实很想解决这个问题！
> 
> 解决方案已经在 #68 中给出。 这是deepin的问题 [#68 (comment)](https://github.com/Icalingua/Icalingua/issues/68#issuecomment-891533310)

好的，谢谢！

**Comment by yimisunrise** [comment]
> @yimisunrise 这是 dde 那边的问题，与我们无关，我们没法修复

OK，知道了！谢谢！
