### ISSUE TITLE
[BUG]运行久了之后，会出现严重卡顿现象

### ISSUE THREAD

**Issue by Mobiacikaka** [Icalingua/Icalingua#370]
**Describe the bug / 描述**
运行两天之后，出现严重卡顿现象。

**To Reproduce / 复现过程**
如题

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
单纯卡顿，没有别的不良反应

**System information / 系统信息**
Arch Linux
2.4.4

**Comment by CoelacanthusHex** [comment]
@Mobiacikaka 建议观察下内存占用，包括electron进程的，我怀疑可能与此有关，比如开启时间较长后只是electron的渲染进程就能占2G内存（同时建议使用 github.com/lilydjwg/swapview 查看下icalingua 是不是有数据被交换出去了，如果要访问的数据被交换出去也可能造成卡顿）

**Comment by Clansty** [comment]
建议闲置的时候按 esc 关闭会话

**Comment by Mobiacikaka** [comment]
感谢
