### ISSUE TITLE
[BUG] 任务栏会出现两个图标

### ISSUE THREAD

**Issue by JiashunLi** [Icalingua/Icalingua#371]
任务栏 最小化图标有两个

![image](https://user-images.githubusercontent.com/38833358/145941767-af1d837b-5c37-41a3-99ab-5f5116776e13.png)

**Comment by aimerneige** [comment]
Please add more information about your system version, desktop enviroment, icalingua version please.

**Comment by CoelacanthusHex** [comment]
请遵守模板填写，提供必要的信息

**Comment by JiashunLi** [comment]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

dock栏托盘区域 会出现两个QQ图标

**To Reproduce / 复现过程**

任何时候，打开即出现

**Expected behavior / 预期的结果**

希望只保留一个

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/38833358/145961140-65ec2c8e-ae47-4783-8698-8be95d99715f.png)


**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

![image](https://user-images.githubusercontent.com/38833358/145961241-c4e3947b-6c44-4d37-8b32-36ef457bce8e.png)


**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

系统是 deepin 20.3 内核 是5.15.1
