### ISSUE TITLE
[BUG] 发送的消息缩进和换行会消失

### ISSUE THREAD

**Issue by CoelacanthusHex** [Icalingua/Icalingua#372]
**Describe the bug / 描述**

在大部分时候（具体条件不明），发送的消息的缩进和换行会消失

**To Reproduce / 复现过程**

发送一条带缩进和换行的消息，简单的例子是一条 PGP 签名消息

**Expected behavior / 预期的结果**

保持原有的换行和缩进

**Screenshots / 截图**

**System information / 系统信息**
 - OS: Arch Linux
 - Version: Rolling

**Additional context / 附加信息**

这个问题已经存在很久了，我曾经在群里反馈过，但无果

**Comment by Clansty** [comment]
@CoelacanthusHex 其实只是显示消失，复制下来是有的。不过首尾的空格会被 trim 掉

**Comment by CoelacanthusHex** [comment]
@Clansty 但是显示效果很重要的，你不能指望我看到一条消息复制出来粘到别的地方再看

**Comment by CoelacanthusHex** [comment]
![图片](https://user-images.githubusercontent.com/43064781/146320780-d8510f40-13c1-4561-ad65-8a37634e8680.png)

**Comment by lomirus** [comment]
换行消失我认为可能是 `breakLine` 的解析问题。我本来想看下 `vac-mod/utils/formatString.js` 的源码排除下 bug 来着，但是发现这部分函数的实现有点复杂，可读性不是很高，建议用 typescript 重构下 🤔

**Comment by luoling8192** [comment]
源码可读性确实不高，因为用的是外部的一个项目，重构的事情已经在进行

**Comment by Clansty** [comment]
已经修复了

**Comment by Clansty** [comment]
已经修复了
