### ISSUE TITLE
[BUG] 点开表情会附带 CSS 文本

### ISSUE THREAD

**Issue by CoelacanthusHex** [Icalingua/Icalingua#375]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

点开表情会附带 CSS 文本

**To Reproduce / 复现过程**

点开一个发送的表情

**Expected behavior / 预期的结果**

只有图片

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![图片](https://user-images.githubusercontent.com/43064781/146661111-fe354d95-0b0d-4d29-8bb3-d00c953125d9.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version rolling

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
@CoelacanthusHex 草 这是更新了没重启嘛
