### ISSUE TITLE
[BUG]无法登录qq

### ISSUE THREAD

**Issue by SmallL-U** [Icalingua/Icalingua#376]
**Describe the bug / 描述**
无法登录qq 清除config之后依然无法登录qq 卡在登录界面

**System information / 系统信息**
 - OS: [Arch Linux]

**Comment by sukanka** [comment]
图呢？或者从终端运行的输出呢？你至少要有一个吧。

**Comment by SmallL-U** [comment]
ok 这就搞

**Comment by SmallL-U** [comment]
![image](https://user-images.githubusercontent.com/61272004/147062778-834a2573-60ae-45bd-9fa4-ffb1668c1bfc.png)

**Comment by Unnamed-1408** [comment]
也出现了这个问题，莫名其妙登录不上去了

**Comment by SmallL-U** [comment]
最开始的时候运行着的 突然发消息的回调出问题了 显示packet 啥的 忘了 然后就关闭软件 无法登录了 清理config也无法登录 重装软件也不行

**Comment by OneRain233** [comment]
确实我也出现这个问题了，莫名其妙登不上+1

**Comment by Integral-Tech** [comment]
Manjaro (Kernel 5.15.7)也登不进去了，重装icalingua、删除config、切换网络环境/代理均无效。

**Comment by lovecodec** [comment]
就是一直卡在登录

**Comment by taostart** [comment]
昨天还可以登陆，只是有点慢，今天完全登陆不了了

**Comment by Clansty** [comment]
有没有人试试 oicq 2.0 能不能登录

**Comment by SmallL-U** [comment]
咋试

**Comment by SmallL-U** [comment]
QR Code Login也获取二维码失败

**Comment by taostart** [comment]
我看上游修复了一个协议更新，看来是时候安排新版本了

**Comment by Clansty** [comment]
@SmallL-U 可以用示例应用登录

**Comment by Clansty** [comment]
@taostart 1.x 的？

**Comment by Clansty** [comment]
@Clansty 是的，有 1.21.3 了，我试试

**Comment by SmallL-U** [comment]
> @SmallL-U 可以用示例应用登录

我现在出来了 你看看他们有没空

**Comment by SmallL-U** [comment]
![image](https://user-images.githubusercontent.com/61272004/147079276-27b57e67-2f46-47bb-a58f-67704d8f9d70.png)
template可以登录

**Comment by Brx86** [comment]
> ![image](https://user-images.githubusercontent.com/61272004/147079276-27b57e67-2f46-47bb-a58f-67704d8f9d70.png) template可以登录 @Clansty

现在新版还没发releases，但可以先手动更新

**Comment by Clansty** [comment]
@Brx86 不用再跟进了，等编译，已经修复了

**Comment by SmallL-U** [comment]
> @Brx86 不用再跟进了，等编译，已经修复了

说起来奇怪(Doge 刚才启动客户端长达一定时间之后它竟然登录进去了

**Comment by Hou-Xiaoxuan** [comment]
> > @Brx86 不用再跟进了，等编译，已经修复了
> 
> 说起来奇怪(Doge 刚才启动客户端长达一定时间之后它竟然登录进去了

我日常启动后等很一段时间窗口才能出来。刚才完全打不开。
不过20多分钟启动的程序，刚才也忽然弹出来了。

**Comment by SmallL-U** [comment]
> > > @Brx86 不用再跟进了，等编译，已经修复了
> > 
> > 
> > 说起来奇怪(Doge 刚才启动客户端长达一定时间之后它竟然登录进去了
> 
> 我日常启动后等很一段时间窗口才能出来。刚才完全打不开。 不过20多分钟启动的程序，刚才也忽然弹出来了。

我日常启动都挺快的 一般启动不起来我都直接杀进程然后删掉.config/icalingua里面的data文件夹 然后就搞定了(Doge 也不会影响数据啥的 那个文件夹存的应该是登录数据
