### ISSUE TITLE
[BUG]突然启动不了了

### ISSUE THREAD

**Issue by GoCross** [Icalingua/Icalingua#377]
**Describe the bug / 描述**
突然启动不了了，ps查看有icalingua进程，但是界面出不来。

**Screenshots / 截图**
没有截图，给个ps -ef的打印吧
/opt/Icalingua/icalingua
/opt/Icalingua/icalingua --type=zygote --no-zygote-sandbox
/opt/Icalingua/icalingua --type=zygote
/opt/Icalingua/icalingua --type=zygote
/opt/Icalingua/icalingua --type=gpu-process --field-trial-handle=9061540146845255057,14287696278398147751,131072 --enable-features=CSSContainerQueries --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files
/opt/Icalingua/icalingua --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=9061540146845255057,14287696278398147751,131072 --enable-features=CSSContainerQueries --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=zh-CN --service-sandbox-type=none --shared-files=v8_context_snapshot_data:100

**System information / 系统信息**
Ubuntu 20.04.3 LTS
之前版本是2.4.3，刚升级了2.4.4也同样

**Comment by SmallL-U** [comment]
你的情况跟我的有点儿像 你看看[无法启动QQ](https://github.com/Icalingua/Icalingua/issues/376)
