### ISSUE TITLE
[BUG]点击Login后无响应

### ISSUE THREAD

**Issue by cmj2002** [Icalingua/Icalingua#378]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
点击Login后无响应
网络状态正常，qq.com可以ping通

**To Reproduce / 复现过程**
选择iPad协议、MacOS协议、或者aPad协议并登录
其他协议目前没有尝试

**Expected behavior / 预期的结果**
无响应

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![](https://picbed.blog.caomingjun.com/2021-12-23_10-11.png)

**System information / 系统信息**
 - OS: kubuntu 20.04LTS
 - Version 2.3.2

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by lovecodec** [comment]
更新到最新版本试试，这个问题已经修复了

**Comment by cmj2002** [comment]
> 更新到最新版本试试，这个问题已经修复了

确实，很抱歉我没有先检查新版本。

谢谢！
