### ISSUE TITLE
[Feature Request] Flatpak build

### ISSUE THREAD

**Issue by catsout** [Icalingua/Icalingua#388]
Please, consider supporting [Flatpak](https://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Icalingua on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by catsout** [comment]
https://github.com/flathub/flathub/pull/2711

**Comment by Clansty** [comment]
I have tried to build a flatpak for Icalingua before, but I found some problems:
- Tray icon blur (can be easily fixed)
- No appmenu support (also can be fixed)
- Issues about reading and browsing local files (need to use XDG portal, it may be a little hard)

**Comment by Clansty** [comment]
If you are interested in contributing Icalingua (eg. crreating a flatpak), you are welcome to PM me (eg. var Email on my profile) to join the Icalingua Insider group.
