### ISSUE TITLE
[BUG] Gnome Shell 下休眠唤醒后出现两个 TrayIcon

### ISSUE THREAD

**Issue by plumlis** [Icalingua/Icalingua#390]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

第一次启动程序 Trayicon 只有一个，没问题
但是一旦笔记本休眠后唤醒，就会变成两个 Trayicon，禁用掉 https://github.com/ubuntu/gnome-shell-extension-appindicator 插件后，还会保留一个 Tray Icon

和之前 DeepinDE 的那个双图标的问题似乎不完全一样。

**To Reproduce / 复现过程**

- 正常运行程序
- 不关闭程序，直接合上盖子让笔记本进入休眠
- 打开盖子，唤醒笔记本，进入系统，看到 Tray Icon 出现两个

**Expected behavior / 预期的结果**

唤醒后依然只有一个 TrayIcon

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/6737429/147810158-763d1a83-fa72-4362-8cbc-a29708c16d8a.png)

**System information / 系统信息**
 **- OS:** Fedora 35 64bit Gnome-shell 41 安装了 https://github.com/ubuntu/gnome-shell-extension-appindicator 插件
 **- Version:**  来自 flathub 的版本 ：https://flathub.org/apps/details/io.github.Icalingua.Icalingua  2.4.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

在日志里看到一些可能有关的内容，唤醒后不能更新状态图标，所以用了某种特殊的方式？

![image](https://user-images.githubusercontent.com/6737429/147810100-dd274b75-f33a-4436-ae88-5e32575f34d5.png)

目前不太确定是不是 Flatpak 程序权限的问题。

**Comment by catsout** [comment]
1. `dbus-monitor > log.txt`
2. `flatpak run --socket=session-bus io.github.Icalingua.Icalingua`  
3. switch dark icon in Trayicon menu
4. ctrl+c `dbus-monitor > log.txt`

Please put the log.txt here

**Comment by catsout** [comment]
Seems `gnome-shell-extension-appindicator` also using `org.kde.StatusNotifierWatcher`  
Please just check whether `flatpak run --talk-name=org.kde.StatusNotifierWatcher io.github.Icalingua.Icalingua` works  
If not, do steps above.

**Comment by plumlis** [comment]
> Seems `gnome-shell-extension-appindicator` also using `org.kde.StatusNotifierWatcher` Please just check whether `flatpak run --talk-name=org.kde.StatusNotifierWatcher io.github.Icalingua.Icalingua` works on switching dark icon in trayicon menu If not, do steps above.

Tired this. It seems works.
So I should add this with my launcher?

**Comment by catsout** [comment]
> So I should add this with my launcher?

You add this through Flatseal.  
This problem will be fixed soon.
