### ISSUE TITLE
[Feature Request] Import db produced by QQ

### ISSUE THREAD

**Issue by starsareintherose** [Icalingua/Icalingua#391]
**Describe the solution you'd like**
from db file to sqlite

**Describe alternatives you've considered**

**Additional context**

**Comment by aimerneige** [comment]
QQ 的数据是加密的，且几乎无法解密。

我记得之前有人发帖希望能够解密自己的聊天文件，并没有得到任何结果。

**Comment by aimerneige** [comment]
刚查了下资料，看雪论坛有逆向大佬做了分析和解密，似乎可行

https://bbs.pediy.com/thread-266370.htm

**Comment by Clansty** [comment]
@aimerneige 不会做，倒是可能可以做导入 txt 消息记录

**Comment by JulianDroske** [comment]
> 

要看是手机端还是电脑端，手机端首先需要得到原设备的IMEI，也就是简单的异或运算
以及部分MobileQQ会将id存放在私有目录中
至于PC QQ有了您提供的链接也就有了解决办法，原理就是hook

**Comment by JulianDroske** [comment]
> 刚查了下资料，看雪论坛有逆向大佬做了分析和解密，似乎可行
> 
> https://bbs.pediy.com/thread-266370.htm

要看是手机端还是电脑端，手机端首先需要得到原设备的IMEI，也就是简单的异或运算
以及部分MobileQQ会将id存放在私有目录中
至于PC QQ有了您提供的链接也就有了解决办法，原理就是hook
