### ISSUE TITLE
[BUG] 数据库操作字段中包含 emoji 会导致服务崩溃

### ISSUE THREAD

**Issue by aimerneige** [Icalingua/Icalingua#392]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

群名片中包含 emoji 字符会导致数据库操作崩溃

**To Reproduce / 复现过程**

群名片中包含 emoji 字符，在该群收发消息即可。

**Expected behavior / 预期的结果**

即使群名片包含 emoji 字符，软件依然可以正常运行。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/51701792/147837717-99791b0b-c46f-4a53-adfc-cc4517357c60.png)

**System information / 系统信息**
 - OS: Ubuntu 20.04.3 LTS x86_64
 - Version dev分支 [03cbfb0cd7c2642eb166280d098e86d44b9a037c](https://github.com/Icalingua/Icalingua/commit/03cbfb0cd7c2642eb166280d098e86d44b9a037c)

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

本来在正式版使用的时候就发现这个 bug 了，就是有个一群死活无法打开和收发消息，没有控制台运行的习惯，也一直不知道是怎么回事，今天配桥接的时候控制台报错被我注意到了。

**Comment by aimerneige** [comment]
![image](https://user-images.githubusercontent.com/51701792/147848658-0267373d-2917-4275-87d2-4f160222f9c3.png)

emoji 似乎导致了更多的问题

**Comment by lixiang810** [comment]
我下周考完，看看两周内能不能修，不能就等 `Icalingua 3` 的重构吧

**Comment by qndydyhm** [comment]
https://dba.stackexchange.com/questions/206478/insert-gives-error-code-1366-incorrect-string-value-xf0-x9f-x98-x80-for-co

**Comment by lixiang810** [comment]
最新的dev分支已经解决了这个问题。

MySQL 用户在建表时请注意设置好编码格式。

**Comment by lixiang810** [comment]
@lixiang810 如果编码不对，il会尝试设置，但不一定成功。

当然最主要的锅不在数据库，而在于与数据库的连接，连接时也要指定编码方式。

两个问题都得到了修复。

**Comment by qndydyhm** [comment]
@lixiang810 锅确实不在数据库，8.0以上的mysql默认都是utf8mb4（
