### ISSUE TITLE
[BUG] 头像无法显示

### ISSUE THREAD

**Issue by justwaterzzf** [Icalingua/Icalingua#396]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
不显示群和人物头像
**To Reproduce / 复现过程**
每次复现
**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![2022-01-05 13-33-19 的屏幕截图](https://user-images.githubusercontent.com/59132399/148165629-f6baec36-2028-48ee-9716-fad132433e8f.png)
**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
Ubuntu 21.10

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
@justwaterzzf 你有没有开代理什么的（

**Comment by Clansty** [comment]
以及 下次请写标题

**Comment by justwaterzzf** [comment]
开了，开代理就出不来了吗？😂😂😂



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 5, 2022 13:39 PM
To: ***@***.***&gt;;
Cc: "RUO ***@***.******@***.***&gt;;
Subject: Re: [Icalingua/Icalingua] [BUG] (Issue #396)




 
@justwaterzzf 你有没有开代理什么的（

**Comment by justwaterzzf** [comment]
哦哦😂



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 5, 2022 13:44 PM
To: ***@***.***&gt;;
Cc: "RUO ***@***.******@***.***&gt;;
Subject: Re: [Icalingua/Icalingua] [BUG] (Issue #396)




 
以及 下次请写标题

**Comment by Clansty** [comment]
最新的 beta 版本应该修复了
