### ISSUE TITLE
[BUG] 从源码构建失败

### ISSUE THREAD

**Issue by qndydyhm** [Icalingua/Icalingua#402]
**Describe the bug / 描述**
使用yarn install构建时安装失败

**To Reproduce / 复现过程**
yarn install

**Expected behavior / 预期的结果**
success

**Screenshots / 截图**
https://drive.marmot.website/s/V1sr

**System information / 系统信息**
 - OS: Arch Linux
 - Version git

**Additional context / 附加信息**
已经魔法上网了应该不存在墙的问题？

**Comment by Clansty** [comment]
换 node 16 试试

**Comment by lomirus** [comment]
测试结果：
```
node: 17.3.0
npm: 8.3.0
yarn: 3.0.0
```
`yarn install` 失败

```
node: 16.13.1
npm: 8.1.2
yarn: 3.0.0
```
`yarn install` 成功

**Comment by lomirus** [comment]
建议在 `package.engine.node` 里明确一下 node 版本要求，以及在 `README.md` contribute 相关部分提一下。

另外本来想试着加个这种 badge 来着：![](https://img.shields.io/node/v/pa11y-webservice)，但是好像看了下貌似只有在 npm 发了包的才能用（（

@Clansty

**Comment by mochaaP** [comment]
upstream: <https://github.com/yarnpkg/berry/issues/3597#issuecomment-955872793>
cc @Clansty please bump
