### ISSUE TITLE
[BUG] Win11 WSLg下无法启动

### ISSUE THREAD

**Issue by peter17ji** [Icalingua/Icalingua#407]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
启动报错
**To Reproduce / 复现过程**
`
peter@TABLET:/mnt/c/Users/peter/Downloads$ sudo apt install ./icalingua_2.4.5_amd64.deb
[sudo] password for peter:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'icalingua' instead of './icalingua_2.4.5_amd64.deb'
The following additional packages will be installed:
  libauthen-sasl-perl libdata-dump-perl libencode-locale-perl libfile-basedir-perl libfile-desktopentry-perl
  libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libhtml-form-perl libhtml-format-perl
  libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-message-perl libhttp-negotiate-perl libio-html-perl libio-socket-ssl-perl libio-stringy-perl
  libipc-system-simple-perl liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libnet-dbus-perl
  libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libtie-ixhash-perl libtimedate-perl libtry-tiny-perl
  liburi-perl libwww-perl libwww-robotrules-perl libx11-protocol-perl libxml-parser-perl libxml-twig-perl
  libxml-xpathengine-perl perl-openssl-defaults xdg-utils
Suggested packages:
  libdigest-hmac-perl libgssapi-perl libcrypt-ssleay-perl libauthen-ntlm-perl libunicode-map8-perl
  libunicode-string-perl xml-twig-tools
The following NEW packages will be installed:
  icalingua libauthen-sasl-perl libdata-dump-perl libencode-locale-perl libfile-basedir-perl libfile-desktopentry-perl
  libfile-listing-perl libfile-mimeinfo-perl libfont-afm-perl libhtml-form-perl libhtml-format-perl
  libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-message-perl libhttp-negotiate-perl libio-html-perl libio-socket-ssl-perl libio-stringy-perl
  libipc-system-simple-perl liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libnet-dbus-perl
  libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libtie-ixhash-perl libtimedate-perl libtry-tiny-perl
  liburi-perl libwww-perl libwww-robotrules-perl libx11-protocol-perl libxml-parser-perl libxml-twig-perl
  libxml-xpathengine-perl perl-openssl-defaults xdg-utils
0 upgraded, 42 newly installed, 0 to remove and 16 not upgraded.
Need to get 2456 kB/87.4 MB of archives.
After this operation, 265 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 xdg-utils all 1.1.3-2ubuntu1.20.04.2 [61.4 kB]
Get:2 http://mirrors.aliyun.com/ubuntu focal/main amd64 libdata-dump-perl all 1.23-1 [27.0 kB]
Get:3 http://mirrors.aliyun.com/ubuntu focal/main amd64 libencode-locale-perl all 1.05-1 [12.3 kB]
Get:4 http://mirrors.aliyun.com/ubuntu focal/main amd64 libipc-system-simple-perl all 1.26-1 [22.8 kB]
Get:5 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-basedir-perl all 0.08-1 [16.9 kB]
Get:6 http://mirrors.aliyun.com/ubuntu focal/main amd64 liburi-perl all 1.76-2 [77.5 kB]
Get:7 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-desktopentry-perl all 0.22-1 [18.2 kB]
Get:8 http://mirrors.aliyun.com/ubuntu focal/main amd64 libtimedate-perl all 2.3200-1 [34.0 kB]
Get:9 http://mirrors.aliyun.com/ubuntu focal/main amd64 libhttp-date-perl all 6.05-1 [9920 B]
Get:10 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-listing-perl all 6.04-1 [9774 B]
Get:11 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-mimeinfo-perl all 0.29-1 [41.5 kB]
Setting up liburi-perl (1.76-2) ...
Setting up libx11-protocol-perl (0.56-7) ...
Setting up libnet-ssleay-perl (1.88-2ubuntu1) ...
Setting up libhttp-date-perl (6.05-1) ...
Setting up libfile-basedir-perl (0.08-1) ...
Setting up libfile-listing-perl (6.04-1) ...
Setting up libnet-http-perl (6.19-1) ...
Setting up libfile-desktopentry-perl (0.22-1) ...
Setting up libwww-robotrules-perl (6.02-1) ...
Setting up libhtml-parser-perl (3.72-5) ...
Setting up icalingua (2.4.5) ...
Setting up libio-socket-ssl-perl (2.067-1) ...
Setting up libhttp-message-perl (6.22-1) ...
Setting up libhtml-form-perl (6.07-1) ...
Setting up libfile-mimeinfo-perl (0.29-1) ...
Setting up libhttp-negotiate-perl (6.01-1) ...
Setting up libhttp-cookies-perl (6.08-1) ...
Setting up libhtml-tree-perl (5.07-2) ...
Setting up libhtml-format-perl (2.12-1) ...
Setting up libnet-smtp-ssl-perl (1.04-1) ...
Setting up libmailtools-perl (2.21-1) ...
Setting up libhttp-daemon-perl (6.06-1) ...
Setting up liblwp-protocol-https-perl (6.07-2ubuntu2) ...
Setting up libwww-perl (6.43-1) ...
Setting up libxml-parser-perl (2.46-1) ...
Setting up libxml-twig-perl (1:3.50-2) ...
Setting up libnet-dbus-perl (1.2.0-1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
peter@TABLET:/mnt/c/Users/peter/Downloads$ icalingua
The futex facility returned an unexpected error code.
Aborted
`
**Expected behavior / 预期的结果**
启动到登录界面
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
peter@TABLET:/mnt/c/Users/peter/Downloads$ uname -a
Linux TABLET 5.10.60.1-microsoft-standard-WSL2 # 1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
peter@TABLET:/mnt/c/Users/peter/Downloads$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

winver
21H2 22000.376

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by aimerneige** [comment]
都有 win 了，用官方客户端吧
