### ISSUE TITLE
[BUG] 联系人搜索框内无法使用ibus输入法

### ISSUE THREAD

**Issue by QRQaccount** [Icalingua/Icalingua#411]
**Describe the bug / 描述**
在搜索好友和搜索群聊的输入框使用ibus输入法输入时输入法无法正常工作。其他输入框（如消息发送框）没有这个问题

**To Reproduce / 复现过程**
打开联系人窗口，切换为ibus拼音输入法，开始输入

**Expected behavior / 预期的结果**
输入法在联系人搜索输入框内能够正常工作，输入中文

**Screenshots / 截图**
出现问题的输入框
![问题](https://user-images.githubusercontent.com/42197951/149456561-bd25bf14-5358-40c7-9c66-2876fd6a4462.png)

正常工作的输入框
![正常](https://user-images.githubusercontent.com/42197951/149456632-c525256a-6d93-4d83-a6cc-3cb796706335.png)

**System information / 系统信息**
 - OS: Fedora 35
 - Version 2.4.5

**Additional context / 附加信息**
输入法为ibus-libpinyin

**Comment by aimerneige** [comment]
ibus-rime 也不行，只能输入英文

**Comment by Clansty** [comment]
可能是因为转换成大写了（

**Comment by AspirinEny** [comment]
arch + gnome 无此问题。

**Comment by QRQaccount** [comment]
更新了一下系统后就好了，不知道为什么，那应该是其他软件的bug。:D
