### ISSUE TITLE
[BUG]软件显示异常，请提供禁用硬件加速选项

### ISSUE THREAD

**Issue by 123ABCDF11345** [Icalingua/Icalingua#416]
**Bug**
软件在运行时“四分五裂”

**Solve Way**
我的系统在运行另一个软件时也出现了这种情况，最后我与这个软件的开发者联系后，确认界面显示异常是因为软件启用了硬件加速（这是一个普遍存在于electron软件中的显示问题，烦请开发者在运行软件时支持一个命令行参数来禁用硬件加速，如
```
./lcalingua -dha
```
对于禁用硬件加速的方法我在electron仓库的issues中找到了 [link](https://github.com/electron/electron/issues/2170#issuecomment-736223269)，您只需要复制到您的项目中就可以，这里再抄一遍：
```

app.disableHardwareAcceleration();

```
（虽然我也很想自己发一个pull requests但是我完全没有vue项目的经验，所以只能烦请您改下代码）

**Comment by Clansty** [comment]
其他人运行时没有这个情况

（我想看一下四分五裂大概是什么样子）

下次更新的时候加上这个参数

**Comment by Clansty** [comment]
以及主进程里面的代码和 vue 是没有关系的qwq

**Comment by Clansty** [comment]
最新的 beta 版已经加入了 `--dha` 开关
