### ISSUE TITLE
[BUG] electron13升级到13.6.8后出现问题

### ISSUE THREAD

**Issue by Brx86** [Icalingua/Icalingua#428]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug 
登陆后大约10秒就会卡住，然后白屏

**To Reproduce / 复现过程**
electron13更新到13.6.8-1 
登陆后大约10秒就会卡住，然后白屏 
清除缓存并重新加载无用，删除~/.config/icalingua的配置文件无用，重启无用
将electron13降级到13.6.7-1不再出现此bug

**Expected behavior / 预期的结果**
正常使用

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图 
窗口白屏
![窗口白屏](https://user-images.githubusercontent.com/44391900/151345859-c2ccced3-bc54-453d-a179-097ff12e953e.png) 
终端启动后白屏时的报错 
![终端启动后白屏时的报错](https://user-images.githubusercontent.com/44391900/151345902-d056ea36-6bb9-464d-a47d-f5f5bbd79ec8.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Version: icalingua 2.4.5-2  electron13 13.6.8-1

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里 
无

**Comment by Brx86** [comment]
多人稳定复现，大概确实是electron13的问题

**Comment by qndydyhm** [comment]
> 多人稳定复现，大概确实是electron13的问题

无法复现，你是[aur](https://aur.archlinux.org/packages/icalingua/)装的吗

**Comment by Brx86** [comment]
刚刚看了下electron13在2022年01月28日 星期五 03时52分18秒又更新了，最新版13.6.8-2不会出现这个bug
（再观察一段时间，如果可以稳定运行的话或许可以关掉这个issue了）

**Comment by Brx86** [comment]
https://bugs.archlinux.org/task/73518
看起来是被修复了
