### ISSUE TITLE
怎么设置缩放和字体呀

### ISSUE THREAD

**Issue by fomxiu1230** [Icalingua/Icalingua#43]

**Comment by Clansty** [comment]
缩放暂不支持，可以用系统的缩放

字体需要把字体文件改名为 `font.ttf` 放在 `~/.config/electron-qq` 目录下

**Comment by fomxiu1230** [comment]
谢谢

**Comment by Leyls** [comment]
~/.config/electron-qq/ 吗？我现在放好字体并且已经重新命名也重启了，但是字体还是原来那样，是需要什么其他设置吗？
另外，我在 .config 文件夹还有发现一个 tencent-qq 文件夹

**Comment by Clansty** [comment]
@Leyls 现在最新的版本已经变成 icalingua 目录了
