### ISSUE TITLE
可以提供arm64和mips64el的包吗

### ISSUE THREAD

**Issue by maxmadzz** [Icalingua/Icalingua#81]
飞腾以及龙芯处理器的用户比较需要

**Comment by CoelacanthusHex** [comment]
可以自己构建（主要是 GitHub Actions 不支持其他架构（我印象里开发者也没有MIPS架构的机器

**Comment by CoelacanthusHex** [comment]
另外求 riscv64 架构的包

**Comment by NO-MEANINGS** [comment]
> 另外求 riscv64 架构的包

开发者好像也没有riscv的机器啊XD

**Comment by sukanka** [comment]
可以用Electron直接运行 app.asar,觉得不方便的话，可以自己打个包。

**Comment by Clansty** [comment]
可以通过 qemu 构建

**Comment by Clansty** [comment]
新的 Pre-release 中已上传 i386 和 arm64 的包，欢迎下载使用
https://github.com/Clansty/Icalingua/releases/tag/2.1.1-dev

另外 MIPS64el 架构我只找到了龙芯官方提供的 10.1.0 版本 Electron，Icalingua 使用了 10.1.0 尚未支持的 API。我非常支持国产 CPU 的开发与使用，接下来将努力适配 10.1.0 版本 Electron 并打包。但我没有设备进行测试，只能由用户自测了。

**Comment by sukanka** [comment]
> 另外 MIPS64el 架构我只找到了龙芯官方提供的 10.1.0 版本 Electron，

能不能请@maxmadzz编译龙芯版的 electron13呢, 官方有 [构建指南](https://www.electronjs.org/docs/development/build-instructions-gn)

**Comment by PigCode** [comment]
可以拿我的机器测试或者编译都可以

**Comment by sukanka** [comment]
> 可以拿我的机器测试或者编译都可以

不可以，昨天我试了交叉编译，到dav1d 那里直接失败， chromium 的dav1d不支持mips,
https://chromium.googlesource.com/chromium/src/+/53a914eac9ec6d2f53b4c17730e2eae348088bcc/third_party/dav1d/config/linux/

**Comment by Clansty** [comment]
@PigCode 请问您的设备是服务器还是普通工作电脑呢

如果是服务器的话或许可以给我开一个 SSH 和 VNC 测试一下

**Comment by PigCode** [comment]
@Clansty 向日葵连接方式发你邮箱了，查收一下

**Comment by Clansty** [comment]
> @Clansty 向日葵连接方式发你邮箱了，查收一下

好，可能明后天我试试

**Comment by axetroy** [comment]
请问可以吧 Electron 的龙芯编译结果分享出来吗

**Comment by Clansty** [comment]
@axetroy 可以啊

**Comment by axetroy** [comment]
> @axetroy 可以啊

非常感谢 :) 可以开个仓库，或者发我邮件吗 axetroy.dev@gmail.com

**Comment by cheungxi** [comment]
@Clansty  我也想要 mips64el的版本

**Comment by Clansty** [comment]
最新 release 中已上传，欢迎下载试用
